from datasets import Dataset, Image
from diffusers import StableDiffusionPipeline

import os


def load_images(text: str, directory: str) -> Dataset:
    """
    Load a local dataset of images and add the same text feature to each item.

    Args:
        text (`str`):
            Text to add as a feature to every item of the dataset.
        directory (`str`):
            Path to the directory containing images to load.

    Returns:
        `Dataset`: Dataset of images and text.
    """

    # Relative paths to image files
    files = [f"{directory}/{file}" for file in os.listdir(directory)]

    # Create the dataset
    return Dataset.from_dict({
        "image": files,
        "text": [text for _ in range(len(files))]
    }).cast_column("image", Image())


def load_original_images(prompts: dict, prompt_name: str) -> Dataset:
    """
    Load the dataset of original data.

    Args:
        prompts (`dict`):
            Mapping of names to prompts.
        prompt_name: (`str`):
            Name of the prompt to use as a feature.

    Returns:
        `Dataset`: Dataset of original data.
    """

    # Load images from original directory
    return load_images(prompts[prompt_name], "data/original")


def load_generated_images(prompts: dict, prompt_name: str, generation: int) -> Dataset:
    """
    Load the dataset generated by the model from a specifed generation.

    Args:
        prompts (`dict`):
            Mapping of names to prompts.
        prompt_name: (`str`):
            Name of the prompt to use as a feature.
        generation: (`int`):
            Generation number.

    Returns:
        `Dataset`: Dataset of generated data.
    """

    # Load images from generation directory
    return load_images(prompts[prompt_name], f"data/gen_{generation}/{prompt_name}")


def generate_and_save_images(
        pipeline: StableDiffusionPipeline,
        prompts: dict,
        prompt_name: str,
        generation: int,
        num_images: int,
        num_inference_steps: int = 10,
) -> None:
    """
    Generate and save images using a Stable Diffusion pipeline.

    Args:
        pipeline (`StableDiffusionPipeline`):
            Stale Diffusion pipeline.
        prompts (`dict`):
            Mapping of names to prompts.
        prompt_name (`str`):
            Name of the prompt to use as input.
        generation (`int`):
            Generation number.
        num_images (`int`):
            Number of images to generate.
        num_inference_steps (`int`, defaults to `10`):
            Number of denoising steps.
    """

    # Create directory to store images
    os.makedirs(f"data/gen_{generation}/{prompt_name}", exist_ok=True)

    # Set UNet in evaulation mode
    pipeline.unet.eval()

    # Generate and save images
    for i in range(num_images):
        image = pipeline(prompts[prompt_name], num_inference_steps=num_inference_steps).images[0]
        image.save(f"data/gen_{generation}/{prompt_name}/{i:04d}.png")
